---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: redis-secondary
spec:
  serviceName: redis-secondary
  replicas: 2
  template:
    metadata:
      labels:
        app: redis-secondary
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: redis-secondary
        image: quay.io/sysdig/redis:3.2-v12.3
        imagePullPolicy: Always
        env:
          - name: REDIS_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: sysdigcloud-config
                key: redis.password
          - name: REPLICA
            value: "true"
        ports:
        - containerPort: 6379
          name: redis-secondary
        volumeMounts:
        - name: redis-secondary-volume
          mountPath: /data
      imagePullSecrets:
        - name: sysdigcloud-pull-secret
  volumeClaimTemplates:
  - metadata:
      name: redis-secondary-volume
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
      storageClassName: <INSERT_YOUR_STORAGE_CLASS_NAME>
