---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: installer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: installer
subjects:
- kind: ServiceAccount
  name: installer
  namespace: sysdigcloud
---
# We need the scc clusterrole to be able to
# grants scc to sysdig service-accounts in
# sysdig namespace.
#
# Starting from OCP 4.6 we already have
# all the built-in clusteroles:
#
# system:openshift:scc:anyuid
# system:openshift:scc:hostaccess
# system:openshift:scc:hostmount
# system:openshift:scc:hostnetwork
# system:openshift:scc:nonroot
# system:openshift:scc:privileged
# system:openshift:scc:restricted
#
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: installer-scc-anyuid
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:anyuid
subjects:
- kind: ServiceAccount
  name: installer
  namespace: sysdigcloud
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: installer-scc-privileged
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:privileged
subjects:
- kind: ServiceAccount
  name: installer
  namespace: sysdigcloud
...
